version: 0.0.2.{build}

cache:
  - src\packages
  
assembly_info:
  patch: true
  file: src\SharedAssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration: Release


build_script:
  - ps: .\build.ps1

test: auto

artifacts:
 - path: build\Aggregates.NET*.nupkg
   name: NuGet
 - path: build\Aggregates.NET.Binaries*.zip
   name: Binaries
 - path: build\Aggregates.NET.Source*.zip
   name: Source
   

deploy:
  - provider: NuGet
    release: v$(version)
    api_key:
      secure: nyYYvfNcljaFo6s6IBdC3lhqwAKOC9HfQjPguKXoHfgs22MwakH+IeXrM2Xn1uc0
    artifact: NuGet
    draft: false
    prerelease: true
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: GitHub
    release: v$(version)
    auth_token:
      secure: E3k8jpbA+1HCY5PHHiUlaOTJVBSlJyGNUGdIAUTStkSs9Aw8b5jYJ8bMZv+9/nb+
    artifact: Binaries, Source
    draft: false
    prerelease: true
    on:
      branch: master
      appveyor_repo_tag: true