version: 0.0.1-build{build}
cache:
  - packages

# branches to build
branches:
  # whitelist
  only:
    - master

# blacklist
  except:
    - gh-pages

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: SharedAssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration: Release


build_script:
- ps: .\build.ps1

test:
  assemblies:
    - src\Aggregates.NET.Unit\bin\%CONFIGURATION%\Aggregates.NET.Unit.dll


artifacts:
 - path: Aggregates.NET*.nupkg
   name: NuGet

deploy:
  - provider: GitHub
    release: v{version}
    auth_token:
      #bsbuild 2014-12-31
      secure: nyYYvfNcljaFo6s6IBdC3lhqwAKOC9HfQjPguKXoHfgs22MwakH+IeXrM2Xn1uc0
    artifact: NuGet
    draft: false
    prerelease: true
    on:
      appveyor_repo_tag: true