cache:
  - packages

# branches to build
branches:
  # whitelist
  only:
    - master

# blacklist
  except:
    - gh-pages

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration: Release

before_build:
  - git remote set-url origin https://github.com/%APPVEYOR_REPO_NAME%.git
  - gitversion /b %APPVEYOR_REPO_BRANCH% /output buildserver
  - nuget restore src\Aggregates.NET.sln

build:
  parallel: true
  project: src\Aggregates.NET.sln


after_build:
  - nuget pack src\Aggregates.NET\Aggregates.NET.nuspec -Properties version=%GitVersion_NuGetVersion%;configuration=%CONFIGURATION%
  - nuget pack src\Aggregates.NET.RavenDB\Aggregates.NET.RavenDB.nuspec -Properties version=%GitVersion_NuGetVersion%;configuration=%CONFIGURATION%

test:
  assemblies:
    - src\Aggregates.NET.Unit\bin\%CONFIGURATION%\Aggregates.NET.Unit.dll

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
 - path: Aggregates.NET*.nupkg
   name: NuGet

deploy:
  - provider: GitHub
    release: v$(GitVersion_NuGetVersion)
    auth_token:
      #bsbuild 2014-12-31
      secure: nyYYvfNcljaFo6s6IBdC3lhqwAKOC9HfQjPguKXoHfgs22MwakH+IeXrM2Xn1uc0
    artifact: NuGet
    draft: false
    prerelease: true
    on:
      appveyor_repo_tag: true